version: 2
project_name: amuxify
before:
  hooks:
    - go mod tidy
builds:
  - id: amuxify
    main: ./cmd/amuxify
    binary: amuxify
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ignore:
      - { goos: darwin, goarch: arm }
      - { goos: windows, goarch: arm }
      - { goos: windows, goarch: arm64 }
    flags: [-trimpath]
    ldflags:
      - -s -w -X github.com/amuxify/amuxify/internal/cli.Version={{.Version}}
archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files: [LICENSE, README.md, CHANGELOG.md, docs/*]
checksum:
  name_template: checksums.txt
  algorithm: sha256
changelog:
  use: github
  sort: asc
release:
  draft: true
  prerelease: auto
