package scan

// Finding codes. These are stable public tokens.
const (
	CodeSymlink        = "SYMLINK"
	CodeEmpty          = "EMPTY_FILE"
	CodeUnreadable     = "UNREADABLE"
	CodeBidiName       = "BIDI_NAME"
	CodeDoubleExt      = "DOUBLE_EXT"
	CodeExecPerm       = "EXEC_PERM"
	CodeExtMismatch    = "EXT_MISMATCH"
	CodeExtUnknown     = "EXT_UNKNOWN"
	CodeDangerous      = "DANGEROUS_CONTENT"
	CodePolyglot       = "POLYGLOT"
	CodeUnparseable    = "UNPARSEABLE"
	CodeNoVideo        = "NO_VIDEO"
	CodeNoAudio        = "NO_AUDIO"
	CodeDataStream     = "DATA_STREAM"
	CodeAttachBlocked  = "ATTACH_BLOCKED"
	CodeAttachExec     = "ATTACH_EXEC"
	CodeAttachDrop     = "ATTACH_DROP"
	CodeAttachOK       = "ATTACH_OK"
	CodeMkvError       = "MKV_ERROR"
	CodeMkvWarning     = "MKV_WARNING"
	CodeTruncated      = "TRUNCATED"
	CodePurchaseAtom   = "PURCHASE_ATOM"
	CodeProvenanceInfo = "PROVENANCE_INFO"
	CodeLinkInTag      = "LINK_IN_TAG"
	CodeLinkInSubs     = "LINK_IN_SUBS"
	CodeDecodeFail     = "DECODE_FAIL"
	CodeNoDuration     = "NO_DURATION"
	CodeClamInfected   = "CLAMAV_INFECTED"
	CodeClamError      = "CLAMAV_ERROR"
	CodeClamMissing    = "CLAMAV_MISSING"
	CodeHardlinked     = "HARDLINKED"
	CodeSidecarBlocked = "SIDECAR_BLOCKED"
	CodeSidecarUnknown = "SIDECAR_UNKNOWN"
	CodeSidecarOK      = "SIDECAR_OK"
	CodeUndTrack       = "UND_TRACK"
	CodeHDR            = "HDR"
	CodeQuarantined    = "QUARANTINED"
)
